name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - pip:
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - matplotlib==3.5.2
    - numpy==1.22.4
    - pandas==1.4.2
    - pillow==9.1.1
    - pip==22.1
    - requests==2.27.1
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - seaborn==0.11.2
    - tensorboard==2.8.0
    - tensorflow==2.8.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - tqdm==4.64.0

# or:
# conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
# python -m pip install tensorflow==2.8.0
# python -m pip install matplotlib==3.5.2 numpy==1.22.4 pandas==1.4.2 pillow==9.1.1 pip==22.1 requests==2.27.1 scikit-learn==1.1.1 scipy==1.8.1 seaborn==0.11.2 tensorboard==2.8.0 tqdm==4.64.0
